/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vijayt' at '26/11/15 12:12 PM' with Gradle 2.6
 *
 * @author vijayt, @date 26/11/15 12:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
 public static void main(String[] args) {
	System.out.println("hii test");
}
}
